# Generated by Django 4.1.6 on 2023-02-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("traits", "0005_remove_trait_pet"),
        ("pets", "0003_alter_pet_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="traits",
            field=models.ManyToManyField(related_name="pets", to="traits.trait"),
        ),
    ]
