# Generated by Django 4.1.6 on 2023-02-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0001_initial"),
        ("traits", "0002_remove_trait_group_trait_pet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trait",
            name="pet",
            field=models.ManyToManyField(related_name="traits", to="pets.pet"),
        ),
    ]
