# Generated by Django 4.1.6 on 2023-02-07 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("traits", "0003_alter_trait_pet"),
    ]

    operations = [
        migrations.AddField(
            model_name="trait",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 2, 7, 22, 30, 19, 384690, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
