# Generated by Django 4.1.6 on 2023-02-09 21:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("traits", "0004_trait_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trait",
            name="pet",
        ),
    ]
